spring.application.name=Stub

stub.delay.base-ms=1000
stub.delay.random-ms=1000

spring.jackson.deserialization.fail-on-unknown-properties=true

management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.show-details=always

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://postgres:5432/mydatabase
spring.datasource.username=user
spring.datasource.password=password